[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "GEMINI_API_KEY,NEXT_PUBLIC_FIREBASE_API_KEY,NEXT_PUBLIC_FIREBASE_APP_ID"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyC4xP7nZlw6tuk6nCIbxMXLwpBasQK75gY"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "hr-prep.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "hr-prep"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "hr-prep.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "542810606488"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:542810606488:web:8e806b8e5b9dda593a39ed"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-9V5NY5TMC3"

[[plugins]]
  package = "@netlify/plugin-nextjs"
